<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8" />
        <title>Exercice require</title>
        <link rel="stylesheet" href="assets/style.css" />
    </head>
    <body>
        <?php 
        require "header.phtml";
        
        $route = isset($_GET["route"]) ? $_GET["route"] : "home" ;
                         //(condition) ? (valeur si vraie) : (valeur si fausse);
        if($route === "home"){
            require "home.phtml";

        } else if($route === "about"){
            require "about.phtml";  
        } else if($route === "contact"){
            require "contact.phtml";
        } else {
            require "home.phtml";
        }
        
        require "footer.phtml";
        ?>
    </body>
</html>


